export const musicData = [{
  'music_id': 1,
  'work_title': 'Ocean by KV',
  'work_content': 'Ocean by KV https://soundcloud.com/kvmusicprod, Creative Commons — Attribution 3.0 Unported  — CC BY 3.0, Free Download / Stream: http://bit.ly/2OCvpHU,   Music promoted by Audio Library https://youtu.be/a8ctDtA7OK8',
  'remaining_time': 172,
  'path': 'music/kv-ocean.mp3',
  'order': 1,
  'is_done': false,
  'completion': '',
  'sheetsOrder': 1
},
{
  'music_id': 2,
  'work_title': 'Oxygen — Scandinavianz',
  'work_content': 'Track: Oxygen — Scandinavianz [Audio Library Release],  Music provided by Audio Library Plus,  Watch: https://youtu.be/w-FQO6RXTjs,  Free Download / Stream: https://alplus.io/Oxygen',
  'remaining_time': 214,
  'path': 'music/Oxygen —  Scandinavianz [Audio Library Release].mp3',
  'order': 1,
  'is_done': false,
  'completion': '',
  'sheetsOrder': 1
},
{
  'music_id': 0,
  'work_title': '',
  'work_content': '',
  'remaining_time': 0,
  'path': '',
  'order': 1,
  'is_done': false,
  'completion': '',
  'sheetsOrder': 1
}]

export const testData = [{
  'work_id': 1,
  'work_title': '每週慢跑30分',
  'work_content': '掌握呼吸節奏，向前邁進',
  'remaining_time': 1800,
  'order': 6,
  'is_done': false,
  'completion': '2019/07/14,2019/07/14',
  'user_id': '1',
  'user_name': 'Tomato man',
  'user_password': '',
  'user_Identity': 'test',
  'sheetsOrder': 1
},
{
  'work_id': 2,
  'work_title': '運動前熱身及伸展',
  'work_content': '做好準備才能保持長久運動習慣',
  'remaining_time': 1800,
  'order': 1,
  'is_done': true,
  'completion': '',
  'user_id': '1',
  'user_name': 'Tomato man',
  'user_password': '',
  'user_Identity': 'test',
  'sheetsOrder': 2
},
{
  'work_id': 3,
  'work_title': '每天閱讀30分',
  'work_content': '睜開眼睛，看向未知的世界',
  'remaining_time': 1800,
  'order': 2,
  'is_done': true,
  'completion': '',
  'user_id': '1',
  'user_name': 'Tomato man',
  'user_password': '',
  'user_Identity': 'test',
  'sheetsOrder': 3
},
{
  'work_id': 4,
  'work_title': '每週練習30分速寫',
  'work_content': '用心取代鏡頭，記錄下感受世界中的美好',
  'remaining_time': 1500,
  'order': 3,
  'is_done': true,
  'completion': '',
  'user_id': '1',
  'user_name': 'Tomato man',
  'user_password': '',
  'user_Identity': 'test',
  'sheetsOrder': 4
},
{
  'work_id': 5,
  'work_title': '與朋友聊聊彼此近況',
  'work_content': '關係是需要持續維持才會永不消逝',
  'remaining_time': 1800,
  'order': 4,
  'is_done': false,
  'completion': '',
  'user_id': '1',
  'user_name': 'Tomato man',
  'user_password': '',
  'user_Identity': 'test',
  'sheetsOrder': 5
},
{
  'work_id': 6,
  'work_title': '摸摸、抱抱、蹭蹭、與寵物玩耍',
  'work_content': '每天都需要的療癒時間',
  'remaining_time': 1800,
  'order': 4,
  'is_done': false,
  'completion': '',
  'user_id': '1',
  'user_name': 'Tomato man',
  'user_password': '',
  'user_Identity': 'test',
  'sheetsOrder': 6
},
{
  'work_id': 7,
  'work_title': '關心重要的人',
  'work_content': '\b因為重要所以更要用心相處',
  'remaining_time': 1800,
  'order': 4,
  'is_done': false,
  'completion': '',
  'user_id': '1',
  'user_name': 'Tomato man',
  'user_password': '',
  'user_Identity': 'test',
  'sheetsOrder': 7
},
{
  'work_id': 8,
  'work_title': '待在外語的世界中',
  'work_content': '語言就跟人一樣，持續保持接觸才會熟悉',
  'remaining_time': 1800,
  'order': 4,
  'is_done': false,
  'completion': '',
  'user_id': '1',
  'user_name': 'Tomato man',
  'user_password': '',
  'user_Identity': 'test',
  'sheetsOrder': 8
}]
